#Using Class

In [9]:
class Employee:
    def __init__(self, name, number, address, salary, post, year_of_joining, education, experience_years):
        self.name = name
        self.number = number
        self.address = address
        self.salary = salary
        self.post = post
        self.year_of_joining = year_of_joining
        self.education = education
        self.experience_years = experience_years

    def describe_employee(self):
        print(f"Employee Name: {self.name}")
        print(f"Employee Number: {self.number}")
        print(f"Address: {self.address}")
        print(f"Salary: {self.salary}")
        print(f"Post: {self.post}")
        print(f"Year of Joining: {self.year_of_joining}")
        print(f"Education: {self.education}")
        print(f"Years of Experience: {self.experience_years}")
        print("-----------")

    def update_year_of_experience(self):
        self.experience_years += 1

    def increase_salary(self, increment):
        self.salary += increment


# Creating an instance called employee101
employee101 = Employee("John Doe", 101, "123 Main St, City", 50000, "Manager", 2015, "MBA", 8)

# Printing individual attributes
print(employee101.name)
print(employee101.number)
print(employee101.address)
print(employee101.salary)

# Calling methods for employee101
employee101.describe_employee()
employee101.increase_salary(5000)  # Increase salary by $5000
employee101.update_year_of_experience()

# After updates
employee101.describe_employee()

# Creating 10 different instances
employees = [
    Employee("Alice Smith", 102, "456 Oak St", 60000, "Engineer", 2018, "BS in Engineering", 5),
    Employee("Bob Johnson", 103, "789 Pine St", 55000, "Accountant", 2017, "CPA", 6),
    Employee("Cathy Lee", 104, "101 Maple St", 48000, "Designer", 2020, "BFA", 3),
    Employee("David Brown", 105, "202 Birch St", 53000, "Marketing", 2019, "MBA", 4),
    Employee("Eve Miller", 106, "303 Cedar St", 59000, "Consultant", 2016, "PhD", 7),
    Employee("Frank Wilson", 107, "404 Elm St", 62000, "Analyst", 2015, "BS in Finance", 9),
    Employee("Grace Evans", 108, "505 Willow St", 50000, "HR", 2018, "MA in HR", 5),
    Employee("Hank Harris", 109, "606 Aspen St", 48000, "IT Support", 2020, "BS in IT", 3),
    Employee("Ivy Lewis", 110, "707 Cypress St", 57000, "Project Manager", 2016, "MBA", 8),
    Employee("Jake Clark", 111, "808 Redwood St", 55000, "Sales", 2017, "BA in Marketing", 6)
]

# Calling describe_employee() for each instance
for emp in employees:
    emp.describe_employee()

# Updating some instances
employees[0].increase_salary(2000)
employees[1].update_year_of_experience()

# Describing updated employees
employees[0].describe_employee()
employees[1].describe_employee()

John Doe
101
123 Main St, City
50000
Employee Name: John Doe
Employee Number: 101
Address: 123 Main St, City
Salary: 50000
Post: Manager
Year of Joining: 2015
Education: MBA
Years of Experience: 8
-----------
Employee Name: John Doe
Employee Number: 101
Address: 123 Main St, City
Salary: 55000
Post: Manager
Year of Joining: 2015
Education: MBA
Years of Experience: 9
-----------
Employee Name: Alice Smith
Employee Number: 102
Address: 456 Oak St
Salary: 60000
Post: Engineer
Year of Joining: 2018
Education: BS in Engineering
Years of Experience: 5
-----------
Employee Name: Bob Johnson
Employee Number: 103
Address: 789 Pine St
Salary: 55000
Post: Accountant
Year of Joining: 2017
Education: CPA
Years of Experience: 6
-----------
Employee Name: Cathy Lee
Employee Number: 104
Address: 101 Maple St
Salary: 48000
Post: Designer
Year of Joining: 2020
Education: BFA
Years of Experience: 3
-----------
Employee Name: David Brown
Employee Number: 105
Address: 202 Birch St
Salary: 53000
Post: Marketing
Year of Joining: 2019
Education: MBA
Years of Experience: 4
-----------
Employee Name: Eve Miller
Employee Number: 106
Address: 303 Cedar St
Salary: 59000
Post: Consultant
Year of Joining: 2016
Education: PhD
Years of Experience: 7
-----------
Employee Name: Frank Wilson
Employee Number: 107
Address: 404 Elm St
Salary: 62000
Post: Analyst
Year of Joining: 2015
Education: BS in Finance
Years of Experience: 9
-----------
Employee Name: Grace Evans
Employee Number: 108
Address: 505 Willow St
Salary: 50000
Post: HR
Year of Joining: 2018
Education: MA in HR
Years of Experience: 5
-----------
Employee Name: Hank Harris
Employee Number: 109
Address: 606 Aspen St
Salary: 48000
Post: IT Support
Year of Joining: 2020
Education: BS in IT
Years of Experience: 3
-----------
Employee Name: Ivy Lewis
Employee Number: 110
Address: 707 Cypress St
Salary: 57000
Post: Project Manager
Year of Joining: 2016
Education: MBA
Years of Experience: 8
-----------
Employee Name: Jake Clark
Employee Number: 111
Address: 808 Redwood St
Salary: 55000
Post: Sales
Year of Joining: 2017
Education: BA in Marketing
Years of Experience: 6
-----------
Employee Name: Alice Smith
Employee Number: 102
Address: 456 Oak St
Salary: 62000
Post: Engineer
Year of Joining: 2018
Education: BS in Engineering
Years of Experience: 5
-----------
Employee Name: Bob Johnson
Employee Number: 103
Address: 789 Pine St
Salary: 55000
Post: Accountant
Year of Joining: 2017
Education: CPA
Years of Experience: 7
-----------

In [11]:
#Without Classes

In [13]:
# Employee data stored as dictionaries
employee101 = {
    "name": "John Doe",
    "number": 101,
    "address": "123 Main St, City",
    "salary": 50000,
    "post": "Manager",
    "year_of_joining": 2015,
    "education": "MBA",
    "experience_years": 8
}

# Function to describe an employee
def describe_employee(emp):
    print(f"Employee Name: {emp['name']}")
    print(f"Employee Number: {emp['number']}")
    print(f"Address: {emp['address']}")
    print(f"Salary: {emp['salary']}")
    print(f"Post: {emp['post']}")
    print(f"Year of Joining: {emp['year_of_joining']}")
    print(f"Education: {emp['education']}")
    print(f"Years of Experience: {emp['experience_years']}")
    print("-----------")

# Function to update years of experience
def update_year_of_experience(emp):
    emp['experience_years'] += 1

# Function to increase salary
def increase_salary(emp, increment):
    emp['salary'] += increment

# Printing individual attributes
print(employee101["name"])
print(employee101["number"])
print(employee101["address"])
print(employee101["salary"])

# Calling functions for employee101
describe_employee(employee101)
increase_salary(employee101, 5000)  # Increase salary by $5000
update_year_of_experience(employee101)

# After updates
describe_employee(employee101)

# Creating 10 different employees
employees = [
    {"name": "Alice Smith", "number": 102, "address": "456 Oak St", "salary": 60000, "post": "Engineer", "year_of_joining": 2018, "education": "BS in Engineering", "experience_years": 5},
    {"name": "Bob Johnson", "number": 103, "address": "789 Pine St", "salary": 55000, "post": "Accountant", "year_of_joining": 2017, "education": "CPA", "experience_years": 6},
    {"name": "Cathy Lee", "number": 104, "address": "101 Maple St", "salary": 48000, "post": "Designer", "year_of_joining": 2020, "education": "BFA", "experience_years": 3},
    {"name": "David Brown", "number": 105, "address": "202 Birch St", "salary": 53000, "post": "Marketing", "year_of_joining": 2019, "education": "MBA", "experience_years": 4},
    {"name": "Eve Miller", "number": 106, "address": "303 Cedar St", "salary": 59000, "post": "Consultant", "year_of_joining": 2016, "education": "PhD", "experience_years": 7},
    {"name": "Frank Wilson", "number": 107, "address": "404 Elm St", "salary": 62000, "post": "Analyst", "year_of_joining": 2015, "education": "BS in Finance", "experience_years": 9},
    {"name": "Grace Evans", "number": 108, "address": "505 Willow St", "salary": 50000, "post": "HR", "year_of_joining": 2018, "education": "MA in HR", "experience_years": 5},
    {"name": "Hank Harris", "number": 109, "address": "606 Aspen St", "salary": 48000, "post": "IT Support", "year_of_joining": 2020, "education": "BS in IT", "experience_years": 3},
    {"name": "Ivy Lewis", "number": 110, "address": "707 Cypress St", "salary": 57000, "post": "Project Manager", "year_of_joining": 2016, "education": "MBA", "experience_years": 8},
    {"name": "Jake Clark", "number": 111, "address": "808 Redwood St", "salary": 55000, "post": "Sales", "year_of_joining": 2017, "education": "BA in Marketing", "experience_years": 6}
]

# Calling describe_employee() for each employee
for emp in employees:
    describe_employee(emp)

# Updating some employees
increase_salary(employees[0], 2000)
update_year_of_experience(employees[1])

# Describing updated employees
describe_employee(employees[0])
describe_employee(employees[1])

John Doe
101
123 Main St, City
50000
Employee Name: John Doe
Employee Number: 101
Address: 123 Main St, City
Salary: 50000
Post: Manager
Year of Joining: 2015
Education: MBA
Years of Experience: 8
-----------
Employee Name: John Doe
Employee Number: 101
Address: 123 Main St, City
Salary: 55000
Post: Manager
Year of Joining: 2015
Education: MBA
Years of Experience: 9
-----------
Employee Name: Alice Smith
Employee Number: 102
Address: 456 Oak St
Salary: 60000
Post: Engineer
Year of Joining: 2018
Education: BS in Engineering
Years of Experience: 5
-----------
Employee Name: Bob Johnson
Employee Number: 103
Address: 789 Pine St
Salary: 55000
Post: Accountant
Year of Joining: 2017
Education: CPA
Years of Experience: 6
-----------
Employee Name: Cathy Lee
Employee Number: 104
Address: 101 Maple St
Salary: 48000
Post: Designer
Year of Joining: 2020
Education: BFA
Years of Experience: 3
-----------
Employee Name: David Brown
Employee Number: 105
Address: 202 Birch St
Salary: 53000
Post: Marketing
Year of Joining: 2019
Education: MBA
Years of Experience: 4
-----------
Employee Name: Eve Miller
Employee Number: 106
Address: 303 Cedar St
Salary: 59000
Post: Consultant
Year of Joining: 2016
Education: PhD
Years of Experience: 7
-----------
Employee Name: Frank Wilson
Employee Number: 107
Address: 404 Elm St
Salary: 62000
Post: Analyst
Year of Joining: 2015
Education: BS in Finance
Years of Experience: 9
-----------
Employee Name: Grace Evans
Employee Number: 108
Address: 505 Willow St
Salary: 50000
Post: HR
Year of Joining: 2018
Education: MA in HR
Years of Experience: 5
-----------
Employee Name: Hank Harris
Employee Number: 109
Address: 606 Aspen St
Salary: 48000
Post: IT Support
Year of Joining: 2020
Education: BS in IT
Years of Experience: 3
-----------
Employee Name: Ivy Lewis
Employee Number: 110
Address: 707 Cypress St
Salary: 57000
Post: Project Manager
Year of Joining: 2016
Education: MBA
Years of Experience: 8
-----------
Employee Name: Jake Clark
Employee Number: 111
Address: 808 Redwood St
Salary: 55000
Post: Sales
Year of Joining: 2017
Education: BA in Marketing
Years of Experience: 6
-----------
Employee Name: Alice Smith
Employee Number: 102
Address: 456 Oak St
Salary: 62000
Post: Engineer
Year of Joining: 2018
Education: BS in Engineering
Years of Experience: 5
-----------
Employee Name: Bob Johnson
Employee Number: 103
Address: 789 Pine St
Salary: 55000
Post: Accountant
Year of Joining: 2017
Education: CPA
Years of Experience: 7
-----------